CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenMovies.Models
{
    public class ApplicationDbContext :DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<MoviesModel> Movies { get; set; }//entre los triangulos va el nombre del modelo y despues va nombre de la tabla de la base de datos
    }
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Models/ErrorViewModel.cs
using System;

namespace ExamenMovies.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Models/MoviesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenMovies.Models
{
    public class MoviesModel
    {
        [Key]
        public int movie_id { get; set; }

        [Required(ErrorMessage = "Enter the Movie name")]
        [Display(Name = "Movie Name")]
        public string movie_name { get; set; }

        [Required(ErrorMessage = "Enter the genere of the movie")]
        [Display(Name = "Genere")]
        public string movie_genere { get; set; }

        [Required(ErrorMessage = "Enter the release year of the movie")]
        [Display(Name = "Year")]
        public int movie_year { get; set; }

        [Required(ErrorMessage = "Enter the calification of the movie")]
        [Display(Name = "Calification")]
        public string movie_calification { get; set; }
    }
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ExamenMovies.Models;

namespace ExamenMovies.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExamenMovies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamenMovies.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MoviesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(string searchString)
        {


            // var displaydata = _db.ClientDb.ToList();// es _db.nombre de la tabla

            var getMoviesdetail = from m in _db.Movies
                                  select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                getMoviesdetail = getMoviesdetail.Where(s => s.movie_name.Contains(searchString));
            }


            return View(await getMoviesdetail.ToListAsync());
        }
        
        public async Task<ActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
;
            }

            var getMovie = await _db.Movies.FindAsync(id);
            return View(getMovie);
        }

        [HttpPost]
        public async Task<ActionResult> Edit (MoviesModel oldMovie)
        {
            if(ModelState.IsValid)
            {
                _db.Update(oldMovie);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldMovie);

        }

        public async Task<ActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getClient = await _db.Movies.FindAsync(id);
            return View(getClient);
        }


        public async Task<ActionResult> Delete(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getClient = await _db.Movies.FindAsync(id);
            return View(getClient);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {

            var getClient = await _db.Movies.FindAsync(id);
            _db.Movies.Remove(getClient);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");


        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(MoviesModel nuevo) //se le pasa algo del tipo del modelo!!!!!!!!!!!
        {
            if (ModelState.IsValid)
            {
                _db.Add(nuevo);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }

            return View(nuevo);
        }
    }
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Movies/Create.cshtml
@model ExamenMovies.Models.MoviesModel

@{
    ViewData["Title"] = "Create";
}

<    <h1>
    <p class="text-white">Create</p>
</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="movie_name" class="text-white"></label>
                <input asp-for="movie_name" class="form-control" />
                <span asp-validation-for="movie_name" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="movie_genere" class="text-white"></label>
                <select class="form-control" name="movie_genere" id="movie">

                    <option value="Action">Action</option>
                    <option value="Adventure">Adventure</option>
                    <option value="Fiction">Fiction</option>
                    <option value="SuperHero">SuperHero</option>
                </select>
                
                <span asp-validation-for="movie_genere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="movie_year" class="text-white"></label>
                <input asp-for="movie_year" class="form-control" />
                <span asp-validation-for="movie_year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="movie_calification" class="text-white"></label>
                <select class="form-control" name="movie_calification" id="calification">

                    <option value="Bad">Bad</option>
                    <option value="Good">Good</option>
                    <option value="Very Good">Very Good</option>
                    <option value="Excellent">Excellent</option>
                </select>

                <span asp-validation-for="movie_calification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Movies/Delete.cshtml
@model ExamenMovies.Models.MoviesModel

@{
    ViewData["Title"] = "Delete";
}

<h1>
    <p class="text-white">Delete</p>
</h1>

<h3>
    <p class="text-white">Are you sure you want to delete this?</p>
</h3>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.movie_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.movie_id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.movie_name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.movie_name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.movie_genere)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.movie_genere)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.movie_year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.movie_year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.movie_calification)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.movie_calification)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Movies/Detail.cshtml
@model ExamenMovies.Models.MoviesModel

@{
    ViewData["Title"] = "Detail";
}

<    <h1>
        <p class="text-white">Movie Detail</p>
    </h1>

     <div background-color: white>
         <hr />
    
             <dl class="row">
                 <dt class="col-sm-2">
                     @Html.DisplayNameFor(model => model.movie_id)
                 </dt>
                 <dd class="col-sm-10">
                     @Html.DisplayFor(model => model.movie_id)
                 </dd>
                 <dt class="col-sm-2">
                     @Html.DisplayNameFor(model => model.movie_name)
                 </dt>
                 <dd class="col-sm-10">
                     @Html.DisplayFor(model => model.movie_name)
                 </dd>
                 <dt class="col-sm-2">
                     @Html.DisplayNameFor(model => model.movie_genere)
                 </dt>
                 <dd class="col-sm-10">
                     @Html.DisplayFor(model => model.movie_genere)
                 </dd>
                 <dt class="col-sm-2">
                     @Html.DisplayNameFor(model => model.movie_year)
                 </dt>
                 <dd class="col-sm-10">
                     @Html.DisplayFor(model => model.movie_year)
                 </dd>
                 <dt class="col-sm-2">
                     @Html.DisplayNameFor(model => model.movie_calification)
                 </dt>
                 <dd class="col-sm-10">
                     @Html.DisplayFor(model => model.movie_calification)
                 </dd>
             </dl>
 
     </div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.movie_id }) |
    <a asp-action="Index">Back to List</a>
</div>

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Movies/Edit.cshtml
@model ExamenMovies.Models.MoviesModel

@{
    ViewData["Title"] = "Edit";
}

<    <h1>
    <p class="text-white">Edit</p>
</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="movie_id" class="text-white"></label>
                <input asp-for="movie_id" class="form-control" readonly />
                <span asp-validation-for="movie_id" class="text-white"></span>
            </div>
            <div class="form-group">
                <label asp-for="movie_name" class="text-white"></label>
                <input asp-for="movie_name" class="form-control" />
                <span asp-validation-for="movie_name" class="text-white"></span>
            </div>
            <div class="form-group">
                <label asp-for="movie_genere" class="text-white"></label>
                <select class="form-control" name="movie_genere" id="movie">

                    <option value="Action">Action</option>
                    <option value="Adventure">Adventure</option>
                    <option value="Fiction">Fiction</option>
                    <option value="SuperHero">SuperHero</option>
                </select>
                <span asp-validation-for="movie_genere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="movie_year" class="text-white"></label>
                <input asp-for="movie_year" class="form-control" />
                <span asp-validation-for="movie_year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="movie_calification" class="text-white"></label>
                <select class="form-control" name="movie_calification" id="calification">

                    <option value="Bad">Bad</option>
                    <option value="Good">Good</option>
                    <option value="Very Good">Very Good</option>
                    <option value="Excellent">Excellent</option>
                </select>
                <span asp-validation-for="movie_calification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Movies/Index.cshtml
@model IEnumerable<ExamenMovies.Models.MoviesModel>

@{
    ViewData["Title"] = "AngelMovies";
}

    <h1>
        <p class="text-white">Angel Prime</p>
    </h1>

<form asp-controller="Movies" asp-action="Index" method="get">
    <p class="text-white">
        Nombre de la pelicula:
        <input type="text" name="SearchString">
        <input type="submit" value="Buscar" />

    </p>

</form>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.movie_id )
            </th>
            <th>
                @Html.DisplayNameFor(model => model.movie_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.movie_genere)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.movie_year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.movie_calification)
            </th>
            <th>
                Options
            </th>
            <th>
                Image
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td bgcolor="#C4E3F3">
                    @Html.DisplayFor(modelItem => item.movie_id)
                </td>
                <td bgcolor="#C4E3F3">
                    @Html.DisplayFor(modelItem => item.movie_name)
                </td>
                <td bgcolor="#C4E3F3">
                    @Html.DisplayFor(modelItem => item.movie_genere)
                </td>
                <td bgcolor="#C4E3F3">
                    @Html.DisplayFor(modelItem => item.movie_year)
                </td>
                <td bgcolor="#C4E3F3">

                    @Html.DisplayFor(modelItem => item.movie_calification)
                </td>
                <td bgcolor="#C4E3F3">
                    @Html.ActionLink("Edit", "Edit", new { id = item.movie_id }, new { @class = "btn btn-primary" }) |

                    @Html.ActionLink("Details", "Detail", new { id = item.movie_id }, new { @class = "btn btn-success" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.movie_id }, new { @class = "btn btn-danger" })
                </td>
                <td bgcolor="#C4E3F3">
                    <img src="https://pbs.twimg.com/profile_images/707484153285988352/BtbCub-r_400x400.jpg" class="rounded float-left" alt="Responsive image">
                </td>

            </tr>
        }
    </tbody>
</table>

CRUD y REST Movies Examen/ExamenMovies/ExamenMovies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenMovies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">ExamenMovies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ExamenMovies - <a asp-area="" asp-controller="Movies" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>